"""Generate FundLens's fictional factsheets and labeled evaluation fixtures."""

from __future__ import annotations

import csv
import json
import math
from dataclasses import dataclass
from datetime import date, datetime, timedelta
from pathlib import Path
from typing import Final

from reportlab.lib.colors import HexColor
from reportlab.lib.enums import TA_RIGHT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import PageBreak, Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

REPOSITORY_ROOT: Final[Path] = Path(__file__).resolve().parents[1]
FACTSHEET_DIRECTORY: Final[Path] = REPOSITORY_ROOT / "sample_data" / "synthetic_factsheets"
EXPECTED_DIRECTORY: Final[Path] = REPOSITORY_ROOT / "sample_data" / "expected_extractions"
PRICE_DIRECTORY: Final[Path] = REPOSITORY_ROOT / "sample_data" / "prices"
SOURCE_NOTICE: Final[str] = "Fictional sample generated by FundLens. Not an investment product."
INK: Final[HexColor] = HexColor("#17211D")
EMERALD: Final[HexColor] = HexColor("#176B56")
MIST: Final[HexColor] = HexColor("#EEEDE7")


@dataclass(frozen=True, slots=True)
class SyntheticFund:
    """Source values for one deterministic synthetic factsheet."""

    name: str
    ticker: str
    isin: str
    reporting_date: str
    objective: str
    strategy: str
    management: str
    benchmark: str
    asset_class: str
    fee_label: str
    fee: str
    income: str
    domicile: str
    base_currency: str
    share_class_currency: str
    fund_size: str
    holdings: tuple[str, ...]
    sectors: tuple[str, ...]
    geographies: tuple[str, ...]
    liquidity: str
    risks: tuple[str, ...]


FUNDS: Final[tuple[SyntheticFund, ...]] = (
    SyntheticFund(
        "Northstar Global Equity Index Fund",
        "NSGE",
        "IE0SYNTH0001",
        "30 June 2026",
        "Track developed-market large and mid-cap equities.",
        "Physical replication with representative sampling.",
        "Passive",
        "Northstar Developed Markets Index (Net)",
        "Global equity",
        "Total expense ratio",
        "0.18%",
        "Accumulating",
        "Ireland",
        "USD",
        "USD",
        "USD 1.24 billion",
        ("Aster Systems 4.8%", "Boreal Health 3.7%", "Cobalt Finance 3.4%"),
        ("Technology 26%", "Financials 17%", "Healthcare 14%"),
        ("United States 64%", "Japan 7%", "United Kingdom 5%"),
        "Exchange traded; indicative spread 0.08%; daily dealing.",
        ("Market risk", "Currency risk", "Tracking difference risk"),
    ),
    SyntheticFund(
        "Harbor Sustainable Dividend ETF",
        "HSDV",
        "LU0SYNTH0002",
        "31 May 2026",
        "Seek income and long-term capital growth from dividend-paying companies.",
        "Rules-based ESG and dividend screen; quarterly rebalance.",
        "Passive",
        "Harbor Sustainable Dividend Index",
        "Global equity income",
        "Ongoing charges figure",
        "0.32%",
        "Distributing",
        "Luxembourg",
        "EUR",
        "EUR",
        "EUR 684 million",
        ("Delphine Utilities 4.2%", "Elm Consumer 3.9%", "Fjord Telecom 3.5%"),
        ("Utilities 21%", "Consumer staples 19%", "Financials 16%"),
        ("Europe 44%", "North America 38%", "Asia Pacific 15%"),
        "Exchange traded; quarterly distribution; normal market hours.",
        ("Equity risk", "ESG methodology risk", "Dividend concentration risk"),
    ),
    SyntheticFund(
        "Meridian Short Duration Bond Fund",
        "MSDB",
        "GB0SYNTH0003",
        "30 June 2026",
        "Preserve capital while generating income from short-duration bonds.",
        "Actively selects investment-grade sovereign and corporate debt.",
        "Active",
        "Three-month Treasury Bill Index",
        "Short-duration fixed income",
        "Annual management charge",
        "0.24%",
        "Distributing",
        "United Kingdom",
        "GBP",
        "GBP",
        "GBP 410 million",
        ("UK Treasury 2028 8.1%", "Granite Bank 2027 3.8%", "Helios Energy 2029 3.2%"),
        ("Sovereign 48%", "Financial credit 23%", "Industrial credit 18%"),
        ("United Kingdom 62%", "United States 16%", "Europe 14%"),
        "Daily dealing before 12:00 London time; not exchange traded.",
        ("Interest-rate risk", "Credit risk", "Liquidity risk"),
    ),
    SyntheticFund(
        "Atlas Emerging Markets Equity ETF",
        "AEME",
        "IE0SYNTH0004",
        "31 March 2026",
        "Track broad emerging-market equity performance.",
        "Optimized physical replication; securities lending permitted.",
        "Passive",
        "Atlas Emerging Markets IMI",
        "Emerging-markets equity",
        "Total expense ratio",
        "0.29%",
        "Accumulating",
        "Ireland",
        "USD",
        "USD",
        "USD 932 million",
        ("Ibis Semiconductor 7.0%", "Jade Commerce 5.8%", "Kite Financial 4.6%"),
        ("Technology 28%", "Financials 22%", "Consumer discretionary 13%"),
        ("China 25%", "India 20%", "Taiwan 18%"),
        "Exchange traded; estimated spread 0.15%; daily creation/redemption.",
        ("Emerging-market risk", "Currency risk", "Political risk", "Securities-lending risk"),
    ),
    SyntheticFund(
        "Cedar Europe Small Companies Fund",
        "CESC",
        "LU0SYNTH0005",
        "30 June 2026",
        "Deliver long-term growth from smaller European companies.",
        "Fundamental, bottom-up portfolio of 45-70 companies.",
        "Active",
        "Cedar Europe Small Cap Index",
        "European small-cap equity",
        "Ongoing charges",
        "0.78%",
        "Accumulating",
        "Luxembourg",
        "EUR",
        "EUR",
        "EUR 255 million",
        ("Lumen Software 3.1%", "Mistral Components 2.9%", "Nacre Medical 2.7%"),
        ("Industrials 25%", "Technology 19%", "Healthcare 16%"),
        ("France 18%", "Germany 17%", "Sweden 13%"),
        "Daily dealing; swing pricing may apply.",
        ("Small-company risk", "Liquidity risk", "Active-management risk"),
    ),
    SyntheticFund(
        "Orchard US Treasury 1-3 Year ETF",
        "OUTS",
        "IE0SYNTH0006",
        "30 June 2026",
        "Track US Treasury securities with one-to-three-year maturities.",
        "Full physical replication where practicable.",
        "Passive",
        "Orchard US Treasury 1-3 Year Index",
        "Government fixed income",
        "Total expense ratio",
        "0.09%",
        "Distributing",
        "Ireland",
        "USD",
        "GBP",
        "USD 1.82 billion",
        (
            "US Treasury 4.25% 2028 12.4%",
            "US Treasury 4.00% 2027 11.7%",
            "US Treasury 3.75% 2029 10.9%",
        ),
        ("Sovereign 100%",),
        ("United States 100%",),
        "Exchange traded in GBP; underlying NAV calculated in USD.",
        ("Interest-rate risk", "Share-class currency risk", "Tracking risk"),
    ),
    SyntheticFund(
        "Pioneer Asia Quality Growth Fund",
        "PAQG",
        "SG0SYNTH0007",
        "31 May 2026",
        "Seek capital appreciation from quality growth companies in Asia.",
        "Concentrated fundamental portfolio with a five-year investment horizon.",
        "Active",
        "Not disclosed",
        "Asia ex-Japan equity",
        "Management fee",
        "1.05%",
        "Accumulating",
        "Singapore",
        "USD",
        "USD",
        "USD 188 million",
        ("Opal Digital 6.2%", "Pine Logistics 5.4%", "Quartz Leisure 4.9%"),
        ("Technology 31%", "Consumer discretionary 20%", "Industrials 14%"),
        ("India 24%", "China 21%", "South Korea 15%"),
        "Weekly dealing; redemption notice may be required for large orders.",
        ("Concentration risk", "Emerging-market risk", "Liquidity risk"),
    ),
    SyntheticFund(
        "Redwood Global Infrastructure ETF",
        "RGIF",
        "IE0SYNTH0008",
        "30 April 2026",
        "Track listed infrastructure companies across developed markets.",
        "Physical sampling subject to liquidity and concentration limits.",
        "Passive",
        "Redwood Global Infrastructure Index",
        "Global infrastructure equity",
        "Ongoing charges figure",
        "0.40%",
        "Distributing",
        "Ireland",
        "USD",
        "EUR",
        "USD 743 million",
        ("River Grid 5.1%", "Summit Towers 4.7%", "Tide Airports 4.0%"),
        ("Utilities 39%", "Industrials 31%", "Energy 17%"),
        ("United States 47%", "Europe 27%", "Canada 11%"),
        "Exchange traded in EUR; semiannual distributions.",
        ("Sector concentration risk", "Currency risk", "Regulatory risk"),
    ),
    SyntheticFund(
        "Solstice Multi-Asset Defensive Fund",
        "SMAD",
        "GB0SYNTH0009",
        "30 June 2026",
        "Target positive returns over rolling three-year periods with lower volatility than global equities.",
        "Actively allocates across bonds, equities, cash and listed alternatives.",
        "Active",
        "SONIA + 2%",
        "Multi-asset",
        "Ongoing charges",
        "0.62%",
        "Accumulating",
        "United Kingdom",
        "GBP",
        "GBP",
        "GBP 521 million",
        (
            "Global Government Bond Basket 18.0%",
            "Developed Equity Basket 14.0%",
            "Cash Instruments 11.0%",
        ),
        ("Fixed income 55%", "Equity 25%", "Alternatives 10%", "Cash 10%"),
        ("Global 100%",),
        "Daily dealing; dilution adjustment may apply.",
        ("Asset-allocation risk", "Derivative risk", "Counterparty risk"),
    ),
    SyntheticFund(
        "Tundra Climate Transition Bond ETF",
        "TCTB",
        "LU0SYNTH0010",
        "31 May 2026",
        "Track investment-grade bonds from issuers aligned with climate-transition criteria.",
        "Rules-based screened sampling; annual climate eligibility review.",
        "Passive",
        "Tundra Climate Transition Bond Index",
        "Sustainable corporate fixed income",
        "Fund expenses",
        "0.22%",
        "Distributing",
        "Luxembourg",
        "EUR",
        "EUR",
        "EUR 306 million",
        ("Umber Rail 2.8%", "Valeo Grid 2.5%", "Willow Housing 2.3%"),
        ("Financial credit 35%", "Industrial credit 33%", "Utilities 24%"),
        ("Europe 67%", "North America 21%", "Asia Pacific 8%"),
        "Exchange traded; underlying bonds may trade less frequently than fund shares.",
        ("Credit risk", "Green methodology risk", "Liquidity mismatch risk"),
    ),
)


def _header_footer(canvas: object, document: SimpleDocTemplate) -> None:
    """Render consistent synthetic-document identity and page numbers."""

    canvas.saveState()
    canvas.setFont("Helvetica", 8)
    canvas.setFillColor(EMERALD)
    canvas.drawString(18 * mm, A4[1] - 12 * mm, "FUNDLENS SYNTHETIC FACTSHEET")
    canvas.setFillColor(INK)
    canvas.drawRightString(A4[0] - 18 * mm, 10 * mm, f"Page {document.page}")
    canvas.restoreState()


def _field_rows(pairs: tuple[tuple[str, str], ...]) -> list[list[str]]:
    """Convert label/value pairs to a ReportLab table payload."""

    return [[label, value] for label, value in pairs]


def _build_pdf(fund: SyntheticFund, destination: Path) -> None:
    """Build a compact three-page text-native factsheet."""

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle("Title", parent=styles["Title"], textColor=INK, fontSize=22)
    section_style = ParagraphStyle("Section", parent=styles["Heading2"], textColor=EMERALD)
    notice_style = ParagraphStyle(
        "Notice", parent=styles["BodyText"], textColor=INK, alignment=TA_RIGHT
    )
    document = SimpleDocTemplate(
        str(destination), pagesize=A4, rightMargin=18 * mm, leftMargin=18 * mm, topMargin=30 * mm
    )
    story: list[object] = [
        Paragraph(fund.name, title_style),
        Paragraph(SOURCE_NOTICE, notice_style),
        Spacer(1, 8 * mm),
        Paragraph("Fund overview", section_style),
    ]
    overview_pairs = (
        ("Ticker", fund.ticker),
        ("ISIN", fund.isin),
        ("Factsheet reporting date", fund.reporting_date),
        ("Investment objective", fund.objective),
        ("Strategy", fund.strategy),
        ("Management approach", fund.management),
        ("Benchmark", fund.benchmark),
        ("Asset class", fund.asset_class),
        (fund.fee_label, fund.fee),
        ("Income treatment", fund.income),
        ("Domicile", fund.domicile),
        ("Base currency", fund.base_currency),
        ("Share-class currency", fund.share_class_currency),
        ("Fund size", fund.fund_size),
    )
    disclosed_overview_pairs = tuple(pair for pair in overview_pairs if pair[1] != "Not disclosed")
    overview = Table(
        _field_rows(disclosed_overview_pairs),
        colWidths=[48 * mm, 112 * mm],
    )
    overview.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (0, -1), MIST),
                ("TEXTCOLOR", (0, 0), (-1, -1), INK),
                ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("GRID", (0, 0), (-1, -1), 0.25, HexColor("#C9CEC9")),
                ("LEFTPADDING", (0, 0), (-1, -1), 8),
                ("RIGHTPADDING", (0, 0), (-1, -1), 8),
                ("TOPPADDING", (0, 0), (-1, -1), 6),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
            ]
        )
    )
    story.extend([overview, PageBreak(), Paragraph("Portfolio and trading", title_style)])
    for heading, entries in (
        ("Top holdings", fund.holdings),
        ("Sector exposure", fund.sectors),
        ("Geographic exposure", fund.geographies),
    ):
        story.extend(
            [
                Paragraph(heading, section_style),
                Paragraph("<br/>".join(entries), styles["BodyText"]),
                Spacer(1, 5 * mm),
            ]
        )
    story.extend(
        [
            Paragraph("Liquidity and trading information", section_style),
            Paragraph(fund.liquidity, styles["BodyText"]),
            PageBreak(),
            Paragraph("Disclosed risks", title_style),
            Paragraph("<br/>".join(f"- {risk}" for risk in fund.risks), styles["BodyText"]),
            Spacer(1, 10 * mm),
            Paragraph("Important information", section_style),
            Paragraph(
                "This document is entirely fictional and exists only to test FundLens. "
                "Past performance is not provided. No NAV or market-price return series is contained in this factsheet. "
                "Nothing here is an offer, recommendation, suitability assessment or financial advice.",
                styles["BodyText"],
            ),
        ]
    )
    document.build(story, onFirstPage=_header_footer, onLaterPages=_header_footer)


def _expected_extraction(fund: SyntheticFund) -> dict[str, object]:
    """Create page labels used by the extraction evaluation harness."""

    reporting_date = datetime.strptime(fund.reporting_date, "%d %B %Y").date().isoformat()
    fund_size_parts = fund.fund_size.split()
    fund_size_multiplier = 1_000_000_000 if fund_size_parts[2] == "billion" else 1_000_000
    normalized_fund_size = {
        "amount": float(fund_size_parts[1]) * fund_size_multiplier,
        "currency": fund_size_parts[0],
        "scope": "fund",
        "original_text": fund.fund_size,
    }

    def normalized_weighted_values(values: tuple[str, ...]) -> list[dict[str, object]]:
        normalized_values: list[dict[str, object]] = []
        for value in values:
            label, weight = value.rsplit(" ", maxsplit=1)
            normalized_values.append(
                {"name": label, "weight_percent": float(weight.removesuffix("%"))}
            )
        return normalized_values

    page_one_fields = {
        "fund_name": fund.name,
        "ticker": fund.ticker,
        "isin": fund.isin,
        "reporting_date": reporting_date,
        "investment_objective": fund.objective,
        "strategy": fund.strategy,
        "management_style": fund.management.lower(),
        "benchmark": fund.benchmark,
        "asset_class": fund.asset_class,
        "expense_ratio": float(fund.fee.removesuffix("%")),
        "original_fee_label": fund.fee_label,
        "income_treatment": fund.income.lower(),
        "domicile": fund.domicile,
        "base_currency": fund.base_currency,
        "share_class_currency": fund.share_class_currency,
        "fund_size": normalized_fund_size,
    }
    fields = {
        key: {"value": value, "page_number": 1, "status": "disclosed"}
        for key, value in page_one_fields.items()
    }
    if fund.benchmark == "Not disclosed":
        fields["benchmark"] = {"value": None, "page_number": None, "status": "not_disclosed"}
    fields.update(
        {
            "top_holdings": {
                "value": normalized_weighted_values(fund.holdings),
                "page_number": 2,
                "status": "disclosed",
            },
            "sector_exposure": {
                "value": normalized_weighted_values(fund.sectors),
                "page_number": 2,
                "status": "disclosed",
            },
            "geographic_exposure": {
                "value": normalized_weighted_values(fund.geographies),
                "page_number": 2,
                "status": "disclosed",
            },
            "liquidity_trading_information": {
                "value": fund.liquidity,
                "page_number": 2,
                "status": "disclosed",
            },
            "disclosed_risks": {"value": list(fund.risks), "page_number": 3, "status": "disclosed"},
        }
    )
    return {"document": f"{fund.ticker.lower()}_factsheet.pdf", "fields": fields}


# Time O(f * d), space O(d): f funds across d generated daily observations.
def _build_price_csv(fund: SyntheticFund, index: int, destination: Path) -> None:
    """Generate a deterministic adjusted-price path for UI and analytics testing."""

    start_date = date(2025, 1, 2)
    price = 90.0 + (index * 4.0)
    rows: list[tuple[str, str]] = []
    business_day_count = 0
    current_date = start_date
    while business_day_count < 320:
        if current_date.weekday() < 5:
            cyclical_return = math.sin((business_day_count + index) / 17.0) * 0.0018
            drift = 0.00012 + (index * 0.00001)
            drawdown_shock = -0.018 if business_day_count in {95 + index, 188} else 0.0
            price *= 1.0 + drift + cyclical_return + drawdown_shock
            rows.append((current_date.isoformat(), f"{price:.4f}"))
            business_day_count += 1
        current_date += timedelta(days=1)

    with destination.open("w", encoding="utf-8", newline="") as csv_file:
        writer = csv.writer(csv_file)
        writer.writerow(("date", "adjusted_close"))
        writer.writerows(rows)


# Time O(f), space O(f): each synthetic fund is generated exactly once.
def generate_dataset() -> None:
    """Regenerate all synthetic PDFs, labels, price files, and the manifest."""

    for directory in (FACTSHEET_DIRECTORY, EXPECTED_DIRECTORY, PRICE_DIRECTORY):
        directory.mkdir(parents=True, exist_ok=True)

    manifest: list[dict[str, str]] = []
    for index, fund in enumerate(FUNDS):
        pdf_name = f"{fund.ticker.lower()}_factsheet.pdf"
        expected_name = f"{fund.ticker.lower()}_expected.json"
        price_name = f"{fund.ticker.lower()}_prices.csv"
        _build_pdf(fund, FACTSHEET_DIRECTORY / pdf_name)
        (EXPECTED_DIRECTORY / expected_name).write_text(
            json.dumps(_expected_extraction(fund), indent=2, ensure_ascii=False) + "\n",
            encoding="utf-8",
        )
        _build_price_csv(fund, index, PRICE_DIRECTORY / price_name)
        manifest.append(
            {
                "ticker": fund.ticker,
                "factsheet": pdf_name,
                "expected_extraction": expected_name,
                "price_data": price_name,
            }
        )

    (REPOSITORY_ROOT / "sample_data" / "manifest.json").write_text(
        json.dumps({"license": "CC0-1.0", "synthetic": True, "funds": manifest}, indent=2) + "\n",
        encoding="utf-8",
    )


if __name__ == "__main__":
    generate_dataset()
